"""Constants for the VSSL Controller integration."""

DOMAIN = "vsslctrl"

SERIAL = "serial"
ZONES = "zones"
MODEL = "model"

INPUT_MODEL = "INPUT_MODEL"
INPUT_ZONE_IP_1 = "INPUT_ZONE_IP_1"
INPUT_ZONE_IP_2 = "INPUT_ZONE_IP_2"
INPUT_ZONE_IP_3 = "INPUT_ZONE_IP_3"
INPUT_ZONE_IP_4 = "INPUT_ZONE_IP_4"
INPUT_ZONE_IP_5 = "INPUT_ZONE_IP_5"
INPUT_ZONE_IP_6 = "INPUT_ZONE_IP_6"
